# Generated by Django 2.2 on 2020-01-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200117_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='follow_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='关注量量'),
        ),
    ]
